races = (
    (1, "Humain"),
    (2, "Elfe"),
    (3, "Nain"),
    (4, "Gnome"),
    (5, "Halfelin"),
    (6, "Demi-Elfe"),
    (7, "Demi-Orc")
)

classes = (
    (1, "Barbare"),
    (2, "Barde"),
    (3, "Druide"),
    (4, "Ensorceleur"),
    (5, "Guerrier"),
    (6, "Magicien"),
    (7, "Moine"),
    (8, "Paladin"),
    (9, "Prêtre"),
    (10, "Rôdeur"),
    (11, "Roublard"),
)

order = (
    (1, "Chaotique"),
    (2, "Neutre"),
    (3, "Loyal"),
)

alignment = (
    (1, "Mauvais"),
    (2, "Neutre"),
    (3, "Bon"),
)

size = (
    ("TP", "Très petit"),
    ("P", "Petit"),
    ("M", "Moyen"),
    ("G", "Grand"),
    ("TG", "Très grand"),
    ("GIG", "Gigantesque"),
    ("C", "Colossal"),
)

xp_table = (
    ("1", "0"),
    ("2", "1000"),
    ("3", "3000"),
    ("4", "6000"),
    ("5", "10000"),
    ("6", "15000"),
    ("7", "21000"),
    ("8", "28000"),
    ("9", "36000"),
    ("10", "45000"),
    ("11", "55000"),
    ("12", "66000"),
    ("13", "78000"),
    ("14", "91000"),
    ("15", "105000"),
    ("16", "120000"),
    ("17", "136000"),
    ("18", "153000"),
    ("19", "171000"),
    ("20", "190000"),
)

languages = (
    ("ABY", "Abyssal"),
    ("AER", "Aérien"),
    ("AQU", "Aquatique"),
    ("CEL", "Céleste"),
    ("DRU", "Druide"),
    ("ELF", "Elfique"),
    ("GEA", "Géants"),
    ("GNOL", "Gnoll"),
    ("GNOM", "Gnome"),
    ("GOB", "Gobelin"),
    ("HAL", "Halfelin"),
    ("IGN", "Igneuse"),
    ("INF", "Infernal"),
    ("NAI", "Nain"),
    ("ORQ", "Orque"),
    ("SYL", "Sylvestre"),
    ("TER", "Terreuse"),
    ("COMPROF", "Commun des profondeurs"),
    ("DRA", "Draconique"),
)

base_skills = [
"acrobaties",
"art_de_la_magie",
"artisanat",
"artisanat_name",
"bluff",
"concentration",
"connaissances_archi",
"connaissances_barb",
"connaissances_folkloc",
"connaissances_geo",
"connaissances_hist",
"connaissances_myst",
"connaissances_nat",
"connaissances_nobl_roy",
"connaissances_relig",
"connaissances_other",
"connaissances_other_name",
"contrefacon",
"crochetage",
"decryptage",
"deguisement",
"deplacemt_sil",
"desarm_sabot",
"detection",
"diplomatie",
"discretion",
"dressage",
"empathie_anim",
"equilibre",
"equitation",
"escalade",
"estimation",
"evasion",
"fouille",
"intimidation",
"langage_secret",
"lecture_levres",
"maitrise_cordes",
"natation",
"percep_audit",
"prem_secours",
"profession",
"profession_name",
"psychologie",
"renseignements",
"representation",
"representation_name",
"saut",
"survie",
"util_obj_magie",
"vol_tire",
]

