from django.db import models


class SkillInventory(models.Model):
    acrobaties = models.IntegerField(default=0)
    art_de_la_magie = models.IntegerField(default=0)
    artisanat = models.IntegerField(default=0)
    artisanat_name = models.CharField(max_length=50)
    bluff = models.IntegerField(default=0)
    concentration = models.IntegerField(default=0)
    connaissances_archi = models.IntegerField(default=0)
    connaissances_barb = models.IntegerField(default=0)
    connaissances_folkloc = models.IntegerField(default=0)
    connaissances_geo = models.IntegerField(default=0)
    connaissances_hist = models.IntegerField(default=0)
    connaissances_myst = models.IntegerField(default=0)
    connaissances_nat = models.IntegerField(default=0)
    connaissances_nobl_roy = models.IntegerField(default=0)
    connaissances_relig = models.IntegerField(default=0)
    connaissances_other = models.IntegerField(default=0)
    connaissances_other_name = models.CharField(max_length=50)  # TODO: create connaissances concept
    contrefacon = models.IntegerField(default=0)
    crochetage = models.IntegerField(default=0)
    decryptage = models.IntegerField(default=0)
    deguisement = models.IntegerField(default=0)
    deplacemt_sil = models.IntegerField(default=0)
    desarm_sabot = models.IntegerField(default=0)
    detection = models.IntegerField(default=0)
    diplomatie = models.IntegerField(default=0)
    discretion = models.IntegerField(default=0)
    dressage = models.IntegerField(default=0)
    empathie_anim = models.IntegerField(default=0)
    equilibre = models.IntegerField(default=0)
    equitation = models.IntegerField(default=0)
    escalade = models.IntegerField(default=0)
    estimation = models.IntegerField(default=0)
    evasion = models.IntegerField(default=0)
    fouille = models.IntegerField(default=0)
    intimidation = models.IntegerField(default=0)
    langage_secret = models.IntegerField(default=0)
    lecture_levres = models.IntegerField(default=0)
    maitrise_cordes = models.IntegerField(default=0)
    natation = models.IntegerField(default=0)
    percep_audit = models.IntegerField(default=0)
    prem_secours = models.IntegerField(default=0)
    profession = models.IntegerField(default=0)
    profession_name = models.CharField(max_length=50)
    psychologie = models.IntegerField(default=0)
    renseignements = models.IntegerField(default=0)
    representation = models.IntegerField(default=0)
    representation_name = models.CharField(max_length=50)
    saut = models.IntegerField(default=0)
    survie = models.IntegerField(default=0)
    util_obj_magie = models.IntegerField(default=0)
    vol_tire = models.IntegerField(default=0)