# Generated by Django 2.0 on 2018-01-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DD35', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='short_name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
