# Generated by Django 2.0 on 2018-01-28 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DD35', '0003_auto_20180123_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='list_of_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
